### ISSUE TITLE
03-live-progress-and-capture-v1.go looks wrong

### ISSUE THREAD

**Issue by dguendisch** [kjk/go-cookbook#3]
New to golang, so bare with me if I don't understand some parts correctly :)
03-live-progress-and-capture-v1.go looks wrong with regards to parallelism:
in line 47 the cmd is actually started, while only _later_ two goroutines try to capture `stdOut` and `stdErr`.
Hence if your computer is slow or loaded, the `cmd` is already finished and `copyAndCapture` will fail to get a hold on anything.
If I add a simple `time.Sleep(100 * time.Millisecond)` after the `cmd.Start()` to simulate slowness, I get two error behaviours from time to time:

1. rarely, but still sometimes `copyAndCapture` will fail to read (in [line 19](https://github.com/kjk/go-cookbook/blob/master/advanced-exec/03-live-progress-and-capture-v1.go#L19)) but get an error `read |0: file already closed`
1. most of the times `copyAndCapture` will miss the output (I didn't understand how that happens): the output is visible in my shell, but `outStr` will be empty, hence no output from the captured string

Now this can be fixed in practice by shifting `cmd.Start()` e.g. to line 56, _after_ the goroutines were started. While that works in practice, I still think it's not absolutely correct as go probably doesn't guarantees when the actual code of a goroutine is executed, so while `cmd.Start()` would appear later in the code, still `copyAndCapture` might be executed "too late".

**Comment by kjk** [comment]
Good catch, thanks for letting me know.

As per `StdoutPipe` docs, the bug/race was: one has to finish reading from pipes before calling `cmd.Wait()` because `Wait` closes pipes.

I've fixed (I think) the examples by using `sync.WaitGroup` to ensure reading from pipes finished before calling `cmd.Wait()`.

I will update the article as well.
