### ISSUE TITLE
free-ssl-certificates: This site can’t provide a secure connection

### ISSUE THREAD

**Issue by suntong** [kjk/go-cookbook#4]
Hi, 

I'm following the `free-ssl-certificates` example, changed `allowedHost` to mine, and it is working, at least for the http part. However, the https part is not working. 

When the program starts, it prints on the console:

```
Starting HTTP server on 127.0.0.1:8080
Starting HTTPS server on :443
```

- Is that normal? Shouldn't HTTPS server has an IP address as well? 
- Visiting http://127.0.0.1:8080 works fine, but when trying to visit https://127.0.0.1:443/, I'll get

        This site can’t provide a secure connection

So, 

- Am I suppose to visit https://127.0.0.1:443/?
- Shall I change more than the `allowedHost`, e.g., the `httpPort` as well? If so, what to change to? 

thx

**Comment by kjk** [comment]
The library in that article provisions Let's Encrypt certificates and they don't work on localhost (127.0.0.1). The only way to test this code via HTTPS (i.e. :443) is on a real site whose DNS name matches allowedHost.

You can learn more at e.g. https://letsencrypt.org/docs/certificates-for-localhost/

Locally you can only test via :8080

**Comment by suntong** [comment]
thanks for the fast response. 

I have a real site whose DNS name matches allowedHost. I've changed `allowedHost` to match, and it is working -- no complaining from the log. 

I don't want it to work on localhost. the localhost is from the `httpPort` line. What else should I change to make it work with real site whose DNS name matches allowedHost? thx

**Comment by suntong** [comment]
> I have a real site whose DNS name matches allowedHost

It has external IP and DNS name, but has `inet 10.0.0.4/24` reported by `ip`.
