### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by suntong** [kjk/go-cookbook#5]
I'm following the free-ssl-certificates example, changed allowedHost to mine and `httpPort` to `:80`, and it is working, at least for the http part. However, the https part is not working.

When the program starts, it prints on the console:
Starting HTTP server on :80
Starting HTTPS server on :443

When using the https connection, 

I'm getting 

```
This site can’t be reached
site took too long to respond.
```

Checking back to the console, I see:

```
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40820: context deadline exceeded
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40826: acme/autocert: missing certificate
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40828: acme/autocert: missing certificate
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40822: acme/autocert: missing certificate
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40830: acme/autocert: missing certificate
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40832: acme/autocert: missing certificate
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40860: acme/autocert: missing certificate
2019/05/07 11:11:11 http: TLS handshake error from 99.xx.xx.221:40824: acme/autocert: missing certificate
```

How to make it works? thx

Once again, I have a real site whose DNS name matches allowedHost. I've changed allowedHost to match, and it is working (by visiting my true DNS name) -- no complaining from the log, even with https.

**Comment by kjk** [comment]
Sorry, I can't debug your issues.

**Comment by suntong** [comment]
Funny, I had a feeling that you'd do this, based on how you closed my previous help request without even trying to understand it.
