### ISSUE TITLE
Incorrect link Code for this chapter: https://github.com/kjk/the-code/tree/master/free-ssl-certificates

### ISSUE THREAD

**Issue by mmullis** [kjk/go-cookbook#7]
Hi. 
on https://blog.kowalczyk.info/article/Jl3G/https-for-free-in-go-with-little-help-of-lets-encrypt.html
this link to code is broken-    https://github.com/kjk/the-code/tree/master/free-ssl-certificates

Missing "/go" in path and should be https://github.com/kjk/the-code/tree/master/go/free-ssl-certificates

**Comment by kjk** [comment]
Fixed, thanks.
